version: 1.0.{build}
image: Visual Studio 2017
environment:
  PROJECTNAME:
    secure: KBAHZmkuYw8zP29yoLEBpA==
  ORGNAME:
    secure: JwKHzxmM+/3pEixMh4+ahdBP/WfaXu8ACXJc6jvs5Eo=
  PROJECTTOKEN:
    secure: PZu/8hX/qN0ts9FhPzAxorVWZq39ihabxmdsoZPgpqnsxQPUQrN9kFue3Qcp9q5r
nuget:
  project_feed: true
  disable_publish_on_pr: true
  disable_publish_octopus: true
before_build:
- ps: >-
    dotnet restore ".\src\AutoMoq.sln"

    nuget restore ".\src\AutoMoq.sln"

    choco install "sonarscanner-msbuild-net46" -y

    SonarScanner.MSBuild.exe begin /k:"$env:PROJECTNAME" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:PROJECTTOKEN" /o:"$env:ORGNAME"
build:
  project: src/AutoMoq.sln
  verbosity: minimal
after_build:
- ps: SonarScanner.MSBuild.exe end /d:"sonar.login=$env:PROJECTTOKEN"
notifications:
- provider: Email
  to:
  - mburton@dennemeyer.com
  - mark.burton@zither-it.co.uk
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false